name: crud_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_check: ^1.0.5
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  get: 4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pdf: ^3.8.1
  pretty_dio_logger: ^1.3.1
  printing: ^5.9.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/note.jpg
